[project]
name = "zbMcLib"
version = "0.0.1"
description = "zbMinecraft库"
requires-python = ">=3.12"
dependencies = [
    "zbToolLib>=1.0.0",
    "lxml>=5.3.0",
    "beautifulsoup4>=4.12.3"
]
authors = [
    { name = "Ianzb", email = "93322252@qq.com" },
]
maintainers = [
    { name = "Ianzb", email = "93322252@qq.com" },
]
readme = "README.md"
license = { text = "MIT License" }
keywords = ["zb", "Ianzb", "Minecraft", "lib"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: Microsoft :: Windows :: Windows 11",
    "Operating System :: Microsoft :: Windows :: Windows 10",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.urls]
Repository = "https://github.com/Ianzb/zbMcLib/"